default_realms = [
            'master', 'main', 'app', 'application', 'prod', 'production',
            'dev', 'development', 'test', 'staging', 'demo', 'admin',
            'api', 'web', 'mobile', 'internal', 'external', 'public', 'portal'
        ]
        
default_client_ids = [
            'account', 'account-console', 'admin-cli', 'broker', 
            'realm-management', 'security-admin-console',
            'app', 'webapp', 'api', 'frontend', 'backend', 
            'mobile-app', 'spa', 'react-app', 'vue-app', 
        ]
        
default_scopes = [
            'openid', 'profile', 'email', 'address', 'phone', 
            'offline_access', 'roles', 'web-origins', 'microprofile-jwt',
            'uma_authorization'
        ]
        
default_idps = [
            'google', 'github', 'facebook', 'twitter', 'linkedin',
            'microsoft', 'bitbucket', 'gitlab', 'instagram', 'paypal',
            'openshift-v3', 'openshift-v4', 'stackoverflow', 
            'oidc', 'saml', 'azure', 'okta', 'auth0', 'apple'
        ]


default_credentials= [
            ('admin', 'admin'),
            ('admin', 'password'),
            ('admin', 'Pa55w0rd'),
            ('admin', 'Password1'),
            ('admin', 'Password123'),
            ('admin', 'admin123'),
            ('admin', 'admin1234'),
            ('admin', 'administrator'),
            ('admin', 'changeit'),
            ('admin', 'changeme'),
            ('admin', ''),
            ('admin', 'Admin123'),
            ('admin', 'Admin@123'),
            ('admin', 'admin@123'),
            ('admin', 'root'),
            ('admin', 'toor'),
            ('admin', 'pass'),
            ('admin', '123456'),
            ('admin', '12345678'),
            ('admin', 'qwerty'),
            ('admin', 'letmein'),
            ('admin', 'welcome'),
            ('admin', 'Welcome1'),
            ('administrator', 'administrator'),
            ('administrator', 'admin'),
            ('administrator', 'password'),
            ('administrator', 'Password1'),
            ('administrator', 'admin123'),
            ('administrator', 'changeit'),
            ('administrator', ''),
            ('keycloak', 'keycloak'),
            ('keycloak', 'password'),
            ('keycloak', 'admin'),
            ('keycloak', 'Pa55w0rd'),
            ('keycloak', 'keycloak123'),
            ('keycloak', 'Keycloak123'),
            ('keycloak', 'changeit'),
            ('keycloak', ''),
            ('root', 'root'),
            ('root', 'admin'),
            ('root', 'password'),
            ('root', 'toor'),
            ('root', 'changeit'),
            ('root', ''),
            ('root', 'Root123'),
            ('user', 'user'),
            ('user', 'password'),
            ('user', 'User123'),
            ('user', ''),
            ('test', 'test'),
            ('test', 'password'),
            ('test', 'test123'),
            ('test', ''),
            ('demo', 'demo'),
            ('demo', 'password'),
            ('demo', 'demo123'),
            ('demo', ''),
            ('service', 'service'),
            ('service', 'password'),
            ('service', 'Service123'),
            ('serviceaccount', 'serviceaccount'),
            ('serviceaccount', 'password'),
            ('svc', 'svc'),
            ('svc', 'password'),
            ('system', 'system'),
            ('system', 'password'),
            ('system', 'manager'),
            ('manager', 'manager'),
            ('manager', 'password'),
            ('manager', 'admin'),
            ('guest', 'guest'),
            ('guest', 'password'),
            ('guest', ''),
            ('app', 'app'),
            ('app', 'password'),
            ('app', 'App123'),
            ('application', 'application'),
            ('application', 'password'),
            ('api', 'api'),
            ('api', 'password'),
            ('api', 'Api123'),
            ('master', 'master'),
            ('master', 'password'),
            ('master', 'admin'),
            ('admin', '1234'),
            ('admin', '12345'),
            ('admin', '123456789'),
            ('admin', 'password123'),
            ('admin', 'Password@1'),
            ('admin', 'P@ssw0rd'),
            ('admin', 'P@ssword'),
            ('admin', 'Passw0rd'),
            ('admin', 'Admin'),
            ('admin', 'ADMIN'),
            ('admin', 'secret'),
            ('admin', 'Secret123'),
            ('admin', 'redhat'),
            ('admin', 'redhat123'),
            ('admin', 'Redhat123'),
            ('rhsso', 'rhsso'),
            ('rhsso', 'password'),
            ('rhsso', 'admin'),
            ('redhat', 'redhat'),
            ('redhat', 'admin'),
            ('admin', 'jboss'),
            ('admin', 'wildfly'),
            ('jboss', 'jboss'),
            ('jboss', 'admin'),
            ('wildfly', 'wildfly'),
            ('wildfly', 'admin'),
            ('admin', '2023'),
            ('admin', '2024'),
            ('admin', '2025'),
            ('admin', 'admin2023'),
            ('admin', 'admin2024'),
            ('admin', 'admin2025'),
            ('admin', 'qwerty123'),
            ('admin', 'qwertyuiop'),
            ('admin', 'azerty'),
            ('admin', 'azerty123'),
            ('admin', '1qaz2wsx'),
            ('admin', 'zxcvbnm'),
            ('admin', 'dragon'),
            ('admin', 'monkey'),
            ('admin', 'master'),
            ('admin', 'sunshine'),
            ('admin', 'princess'),
            ('admin', 'football'),
            ('admin', 'shadow'),
            ('admin', 'superman'),
            ('dev', 'dev'),
            ('dev', 'developer'),
            ('dev', 'password'),
            ('developer', 'developer'),
            ('developer', 'password'),
            ('testuser', 'testuser'),
            ('testuser', 'password'),
            ('testuser', 'test'),
            ('testadmin', 'testadmin'),
            ('testadmin', 'password'),
            ('prod', 'prod'),
            ('prod', 'production'),
            ('prod', 'password'),
            ('staging', 'staging'),
            ('staging', 'password'),
            ('backup', 'backup'),
            ('backup', 'password'),
            ('maintenance', 'maintenance'),
            ('maintenance', 'password'),
            ('support', 'support'),
            ('support', 'password'),
            ('anonymous', 'anonymous'),
            ('admin', None),
            ('anonymous', 'admin'),
        ]